### ISSUE TITLE
How do periodic updates work? 

### ISSUE THREAD

**Issue by krrishdholakia** [Infisical/infisical-python#54]
How does my server get the new api key when: 
- I update it on infisical 
- I **don't** restart my server

**Comment by krrishdholakia** [comment]
cc: @vmatsiiako @dangtony98

**Comment by krrishdholakia** [comment]
Never mind - found the logic - thanks!

**Comment by vmatsiiako** [comment]
Great! Sorry for the slow reply. Let us know if w can help with anything else!
